package lugang.app.huansi.net.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import lugang.app.huansi.net.db.MeasureDataInSQLite;
import lugang.app.huansi.net.db.MeasureOrderDtlRemarkBaseInSQLite;
import lugang.app.huansi.net.db.MeasureOrderDtlStyleBaseDataInSQLite;
import lugang.app.huansi.net.db.MeasureOrderInSQLite;
import lugang.app.huansi.net.db.MeasureRemarkDataInSQLite;
import lugang.app.huansi.net.db.RemarkCategoryDataInSQLite;
import lugang.app.huansi.net.db.RemarkDetailDataInSQLite;

import lugang.app.huansi.net.greendao.MeasureDataInSQLiteDao;
import lugang.app.huansi.net.greendao.MeasureOrderDtlRemarkBaseInSQLiteDao;
import lugang.app.huansi.net.greendao.MeasureOrderDtlStyleBaseDataInSQLiteDao;
import lugang.app.huansi.net.greendao.MeasureOrderInSQLiteDao;
import lugang.app.huansi.net.greendao.MeasureRemarkDataInSQLiteDao;
import lugang.app.huansi.net.greendao.RemarkCategoryDataInSQLiteDao;
import lugang.app.huansi.net.greendao.RemarkDetailDataInSQLiteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig measureDataInSQLiteDaoConfig;
    private final DaoConfig measureOrderDtlRemarkBaseInSQLiteDaoConfig;
    private final DaoConfig measureOrderDtlStyleBaseDataInSQLiteDaoConfig;
    private final DaoConfig measureOrderInSQLiteDaoConfig;
    private final DaoConfig measureRemarkDataInSQLiteDaoConfig;
    private final DaoConfig remarkCategoryDataInSQLiteDaoConfig;
    private final DaoConfig remarkDetailDataInSQLiteDaoConfig;

    private final MeasureDataInSQLiteDao measureDataInSQLiteDao;
    private final MeasureOrderDtlRemarkBaseInSQLiteDao measureOrderDtlRemarkBaseInSQLiteDao;
    private final MeasureOrderDtlStyleBaseDataInSQLiteDao measureOrderDtlStyleBaseDataInSQLiteDao;
    private final MeasureOrderInSQLiteDao measureOrderInSQLiteDao;
    private final MeasureRemarkDataInSQLiteDao measureRemarkDataInSQLiteDao;
    private final RemarkCategoryDataInSQLiteDao remarkCategoryDataInSQLiteDao;
    private final RemarkDetailDataInSQLiteDao remarkDetailDataInSQLiteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        measureDataInSQLiteDaoConfig = daoConfigMap.get(MeasureDataInSQLiteDao.class).clone();
        measureDataInSQLiteDaoConfig.initIdentityScope(type);

        measureOrderDtlRemarkBaseInSQLiteDaoConfig = daoConfigMap.get(MeasureOrderDtlRemarkBaseInSQLiteDao.class).clone();
        measureOrderDtlRemarkBaseInSQLiteDaoConfig.initIdentityScope(type);

        measureOrderDtlStyleBaseDataInSQLiteDaoConfig = daoConfigMap.get(MeasureOrderDtlStyleBaseDataInSQLiteDao.class).clone();
        measureOrderDtlStyleBaseDataInSQLiteDaoConfig.initIdentityScope(type);

        measureOrderInSQLiteDaoConfig = daoConfigMap.get(MeasureOrderInSQLiteDao.class).clone();
        measureOrderInSQLiteDaoConfig.initIdentityScope(type);

        measureRemarkDataInSQLiteDaoConfig = daoConfigMap.get(MeasureRemarkDataInSQLiteDao.class).clone();
        measureRemarkDataInSQLiteDaoConfig.initIdentityScope(type);

        remarkCategoryDataInSQLiteDaoConfig = daoConfigMap.get(RemarkCategoryDataInSQLiteDao.class).clone();
        remarkCategoryDataInSQLiteDaoConfig.initIdentityScope(type);

        remarkDetailDataInSQLiteDaoConfig = daoConfigMap.get(RemarkDetailDataInSQLiteDao.class).clone();
        remarkDetailDataInSQLiteDaoConfig.initIdentityScope(type);

        measureDataInSQLiteDao = new MeasureDataInSQLiteDao(measureDataInSQLiteDaoConfig, this);
        measureOrderDtlRemarkBaseInSQLiteDao = new MeasureOrderDtlRemarkBaseInSQLiteDao(measureOrderDtlRemarkBaseInSQLiteDaoConfig, this);
        measureOrderDtlStyleBaseDataInSQLiteDao = new MeasureOrderDtlStyleBaseDataInSQLiteDao(measureOrderDtlStyleBaseDataInSQLiteDaoConfig, this);
        measureOrderInSQLiteDao = new MeasureOrderInSQLiteDao(measureOrderInSQLiteDaoConfig, this);
        measureRemarkDataInSQLiteDao = new MeasureRemarkDataInSQLiteDao(measureRemarkDataInSQLiteDaoConfig, this);
        remarkCategoryDataInSQLiteDao = new RemarkCategoryDataInSQLiteDao(remarkCategoryDataInSQLiteDaoConfig, this);
        remarkDetailDataInSQLiteDao = new RemarkDetailDataInSQLiteDao(remarkDetailDataInSQLiteDaoConfig, this);

        registerDao(MeasureDataInSQLite.class, measureDataInSQLiteDao);
        registerDao(MeasureOrderDtlRemarkBaseInSQLite.class, measureOrderDtlRemarkBaseInSQLiteDao);
        registerDao(MeasureOrderDtlStyleBaseDataInSQLite.class, measureOrderDtlStyleBaseDataInSQLiteDao);
        registerDao(MeasureOrderInSQLite.class, measureOrderInSQLiteDao);
        registerDao(MeasureRemarkDataInSQLite.class, measureRemarkDataInSQLiteDao);
        registerDao(RemarkCategoryDataInSQLite.class, remarkCategoryDataInSQLiteDao);
        registerDao(RemarkDetailDataInSQLite.class, remarkDetailDataInSQLiteDao);
    }
    
    public void clear() {
        measureDataInSQLiteDaoConfig.getIdentityScope().clear();
        measureOrderDtlRemarkBaseInSQLiteDaoConfig.getIdentityScope().clear();
        measureOrderDtlStyleBaseDataInSQLiteDaoConfig.getIdentityScope().clear();
        measureOrderInSQLiteDaoConfig.getIdentityScope().clear();
        measureRemarkDataInSQLiteDaoConfig.getIdentityScope().clear();
        remarkCategoryDataInSQLiteDaoConfig.getIdentityScope().clear();
        remarkDetailDataInSQLiteDaoConfig.getIdentityScope().clear();
    }

    public MeasureDataInSQLiteDao getMeasureDataInSQLiteDao() {
        return measureDataInSQLiteDao;
    }

    public MeasureOrderDtlRemarkBaseInSQLiteDao getMeasureOrderDtlRemarkBaseInSQLiteDao() {
        return measureOrderDtlRemarkBaseInSQLiteDao;
    }

    public MeasureOrderDtlStyleBaseDataInSQLiteDao getMeasureOrderDtlStyleBaseDataInSQLiteDao() {
        return measureOrderDtlStyleBaseDataInSQLiteDao;
    }

    public MeasureOrderInSQLiteDao getMeasureOrderInSQLiteDao() {
        return measureOrderInSQLiteDao;
    }

    public MeasureRemarkDataInSQLiteDao getMeasureRemarkDataInSQLiteDao() {
        return measureRemarkDataInSQLiteDao;
    }

    public RemarkCategoryDataInSQLiteDao getRemarkCategoryDataInSQLiteDao() {
        return remarkCategoryDataInSQLiteDao;
    }

    public RemarkDetailDataInSQLiteDao getRemarkDetailDataInSQLiteDao() {
        return remarkDetailDataInSQLiteDao;
    }

}
