package lugang.app.huansi.net.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import lugang.app.huansi.net.db.MeasureRemarkDataInSQLite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEASURE_REMARK_DATA_IN_SQLITE".
*/
public class MeasureRemarkDataInSQLiteDao extends AbstractDao<MeasureRemarkDataInSQLite, Long> {

    public static final String TABLENAME = "MEASURE_REMARK_DATA_IN_SQLITE";

    /**
     * Properties of entity MeasureRemarkDataInSQLite.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Person = new Property(2, String.class, "person", false, "PERSON");
        public final static Property UserGUID = new Property(3, String.class, "userGUID", false, "USER_GUID");
        public final static Property OrderId = new Property(4, String.class, "orderId", false, "ORDER_ID");
        public final static Property IOrderDtlId = new Property(5, String.class, "iOrderDtlId", false, "I_ORDER_DTL_ID");
        public final static Property StyleId = new Property(6, String.class, "styleId", false, "STYLE_ID");
        public final static Property IId = new Property(7, String.class, "iId", false, "I_ID");
        public final static Property SMeterMarkCode = new Property(8, String.class, "sMeterMarkCode", false, "S_METER_MARK_CODE");
        public final static Property SMeterMarkName = new Property(9, String.class, "sMeterMarkName", false, "S_METER_MARK_NAME");
    };


    public MeasureRemarkDataInSQLiteDao(DaoConfig config) {
        super(config);
    }
    
    public MeasureRemarkDataInSQLiteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEASURE_REMARK_DATA_IN_SQLITE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"PERSON\" TEXT," + // 2: person
                "\"USER_GUID\" TEXT," + // 3: userGUID
                "\"ORDER_ID\" TEXT," + // 4: orderId
                "\"I_ORDER_DTL_ID\" TEXT," + // 5: iOrderDtlId
                "\"STYLE_ID\" TEXT," + // 6: styleId
                "\"I_ID\" TEXT," + // 7: iId
                "\"S_METER_MARK_CODE\" TEXT," + // 8: sMeterMarkCode
                "\"S_METER_MARK_NAME\" TEXT);"); // 9: sMeterMarkName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEASURE_REMARK_DATA_IN_SQLITE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MeasureRemarkDataInSQLite entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String person = entity.getPerson();
        if (person != null) {
            stmt.bindString(3, person);
        }
 
        String userGUID = entity.getUserGUID();
        if (userGUID != null) {
            stmt.bindString(4, userGUID);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(5, orderId);
        }
 
        String iOrderDtlId = entity.getIOrderDtlId();
        if (iOrderDtlId != null) {
            stmt.bindString(6, iOrderDtlId);
        }
 
        String styleId = entity.getStyleId();
        if (styleId != null) {
            stmt.bindString(7, styleId);
        }
 
        String iId = entity.getIId();
        if (iId != null) {
            stmt.bindString(8, iId);
        }
 
        String sMeterMarkCode = entity.getSMeterMarkCode();
        if (sMeterMarkCode != null) {
            stmt.bindString(9, sMeterMarkCode);
        }
 
        String sMeterMarkName = entity.getSMeterMarkName();
        if (sMeterMarkName != null) {
            stmt.bindString(10, sMeterMarkName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MeasureRemarkDataInSQLite entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String person = entity.getPerson();
        if (person != null) {
            stmt.bindString(3, person);
        }
 
        String userGUID = entity.getUserGUID();
        if (userGUID != null) {
            stmt.bindString(4, userGUID);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(5, orderId);
        }
 
        String iOrderDtlId = entity.getIOrderDtlId();
        if (iOrderDtlId != null) {
            stmt.bindString(6, iOrderDtlId);
        }
 
        String styleId = entity.getStyleId();
        if (styleId != null) {
            stmt.bindString(7, styleId);
        }
 
        String iId = entity.getIId();
        if (iId != null) {
            stmt.bindString(8, iId);
        }
 
        String sMeterMarkCode = entity.getSMeterMarkCode();
        if (sMeterMarkCode != null) {
            stmt.bindString(9, sMeterMarkCode);
        }
 
        String sMeterMarkName = entity.getSMeterMarkName();
        if (sMeterMarkName != null) {
            stmt.bindString(10, sMeterMarkName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MeasureRemarkDataInSQLite readEntity(Cursor cursor, int offset) {
        MeasureRemarkDataInSQLite entity = new MeasureRemarkDataInSQLite( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // person
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // userGUID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // orderId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // iOrderDtlId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // styleId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // iId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sMeterMarkCode
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // sMeterMarkName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MeasureRemarkDataInSQLite entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setPerson(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserGUID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOrderId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIOrderDtlId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStyleId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSMeterMarkCode(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSMeterMarkName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MeasureRemarkDataInSQLite entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MeasureRemarkDataInSQLite entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
