package lugang.app.huansi.net.lugang.bean;

import huansi.net.qianjingapp.entity.WsData;

/**
 * Created by Tony on 2017/9/19.
 * 16:07
 * {
 "STATUS": "0",
 "DATA": [
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "12",
 "ISDSTYLETYPEITEMDTLID": "1001",
 "ISDORDERMETERDTLDETAILID": "1001"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "14",
 "ISDSTYLETYPEITEMDTLID": "1001",
 "ISDORDERMETERDTLDETAILID": "1001"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "96",
 "ISDSTYLETYPEITEMDTLID": "1002",
 "ISDORDERMETERDTLDETAILID": "1002"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "36",
 "ISDSTYLETYPEITEMDTLID": "1002",
 "ISDORDERMETERDTLDETAILID": "1002"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "52",
 "ISDSTYLETYPEITEMDTLID": "1003",
 "ISDORDERMETERDTLDETAILID": "1003"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "25",
 "ISDSTYLETYPEITEMDTLID": "1003",
 "ISDORDERMETERDTLDETAILID": "1003"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "85",
 "ISDSTYLETYPEITEMDTLID": "1004",
 "ISDORDERMETERDTLDETAILID": "1004"
 },
 {
 "ISDSTYLETYPEMSTID": "1006",
 "ISMETERSIZE": "55",
 "ISDSTYLETYPEITEMDTLID": "1004",
 "ISDORDERMETERDTLDETAILID": "1004"
 }
 ]
 }
 */

public class MeasureDateBean extends WsData {
    public String ISDSTYLETYPEMSTID="";//款式ID
    public String ISMETERSIZE="";//尺寸
    public String ISDSTYLETYPEITEMDTLID="";//款式明细ID
    public String ISDORDERMETERDTLDETAILID=""; //订单款式明细中的ID
}
